uploads = []
outputs = []

[[generated]]
id = "Xiyzxt7ZQJ_9vI-b61Djx"
uri = "file://artifacts/france-royal/src/assets/politicians/zemmour.png"
type = "image"
title = "generated_image"

[[generated]]
id = "hkSnB8D7QO43ac2Pg18R1"
uri = "file://artifacts/france-royal/src/assets/politicians/marine.png"
type = "image"
title = "generated_image"

[[generated]]
id = "lx1WJxKdOZ7viD2sK_qP5"
uri = "file://artifacts/france-royal/src/assets/politicians/melenchon.png"
type = "image"
title = "generated_image"

[[generated]]
id = "xRJX5urSnQ09EtZmy7Zhj"
uri = "file://artifacts/france-royal/src/assets/politicians/macron.png"
type = "image"
title = "generated_image"

[[generated]]
id = "JreV-SJ4Zd-WNCm2bJ_hX"
uri = "file://artifacts/france-royal/src/assets/politicians/bardella.png"
type = "image"
title = "generated_image"

[[generated]]
id = "BbbL14Y1Jntw6f9TN-wNK"
uri = "file://artifacts/france-royal/src/assets/politicians/piaf.png"
type = "image"
title = "generated_image"

[[generated]]
id = "RYKDizkddbKupBlBZggH5"
uri = "file://artifacts/france-royal/src/assets/politicians/bardot.png"
type = "image"
title = "generated_image"

[[generated]]
id = "yIl1VnXkTdEN8ogCsY3Bq"
uri = "file://artifacts/france-royal/src/assets/politicians/sarkozy.png"
type = "image"
title = "generated_image"

[[generated]]
id = "uSeXtEOY0DL2PI63RTQwN"
uri = "file://artifacts/france-royal/src/assets/politicians/hollande.png"
type = "image"
title = "generated_image"

[[generated]]
id = "OVhQqZOAmHhUw7BhvsEAi"
uri = "file://artifacts/france-royal/src/assets/politicians/gilets.png"
type = "image"
title = "generated_image"

[[generated]]
id = "zzyaHlrMylWkzvzBHGYPb"
uri = "file://artifacts/france-royal/src/assets/politicians/taxe.png"
type = "image"
title = "generated_image"

[[generated]]
id = "rpLYh4ArSonfyi1Yuce_k"
uri = "file://artifacts/france-royal/src/assets/politicians/chirac.png"
type = "image"
title = "generated_image"

[[generated]]
id = "DD8BbXFTv0pmfnVEMdqvo"
uri = "file://artifacts/france-royal/src/assets/politicians/jmlepen.png"
type = "image"
title = "generated_image"

[[generated]]
id = "-lXY5blAcdAHhr9n368xJ"
uri = "file://artifacts/france-royal/src/assets/politicians/philippe.png"
type = "image"
title = "generated_image"

[[generated]]
id = "k20XKiT9ftxZz2MgAR9wu"
uri = "file://artifacts/france-royal/src/assets/politicians/degaulle.png"
type = "image"
title = "generated_image"

[[generated]]
id = "zUwzq3CIgaR3f82r8QdUC"
uri = "file://artifacts/france-royal/src/assets/politicians/mitterrand.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Da5ugv_ZqecA-Y2OfEu2e"
uri = "file://artifacts/france-royal/src/assets/politicians/giscard.png"
type = "image"
title = "generated_image"

[[generated]]
id = "6rCBZkwIae2yALvag_8xl"
uri = "file://artifacts/france-royal/src/assets/politicians/pompidou.png"
type = "image"
title = "generated_image"

[[generated]]
id = "2vgLY0uaWv9O1nLKjB_v2"
uri = "file://artifacts/france-royal/src/assets/politicians/napoleon.png"
type = "image"
title = "generated_image"

[[generated]]
id = "bLyesZdqBZGCM-FZUa7Fm"
uri = "file://artifacts/france-royal/src/assets/politicians/jeanne.png"
type = "image"
title = "generated_image"

[[generated]]
id = "tq69kueGl0gd1KuZ7No7p"
uri = "file://artifacts/france-royal/src/assets/politicians/louis14.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Jjdabc4ImiYiLgsG7Yj4E"
uri = "file://artifacts/france-royal/src/assets/politicians/robespierre.png"
type = "image"
title = "generated_image"

[[generated]]
id = "nWjbxBAEMi-_WjTEkfHL0"
uri = "file://artifacts/france-royal/src/assets/politicians/danton.png"
type = "image"
title = "generated_image"

[[generated]]
id = "DzFTbdTiv77nxSQh0pbNE"
uri = "file://artifacts/france-royal/src/assets/politicians/attal.png"
type = "image"
title = "generated_image"

[[generated]]
id = "hwP5xMb2q2XdfrkIjocmu"
uri = "file://artifacts/france-royal/src/assets/politicians/borne.png"
type = "image"
title = "generated_image"

[[generated]]
id = "gq7vry1tTCoatEk4h2Ff5"
uri = "file://artifacts/france-royal/src/assets/politicians/castex.png"
type = "image"
title = "generated_image"

[[generated]]
id = "sKqZKGT-QWGgry0s6QA_m"
uri = "file://artifacts/france-royal/src/assets/politicians/valls.png"
type = "image"
title = "generated_image"

[[generated]]
id = "zo6l6Y36gJNvkyuyICgFU"
uri = "file://artifacts/france-royal/src/assets/politicians/royal.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Z6QMwFJQYW3nnrU2I5Oaw"
uri = "file://artifacts/france-royal/src/assets/politicians/fillon.png"
type = "image"
title = "generated_image"

[[generated]]
id = "7PZ8Cc562CxI9DuAwIMtE"
uri = "file://artifacts/france-royal/src/assets/politicians/lemaire.png"
type = "image"
title = "generated_image"

[[generated]]
id = "2z5g2Rr29WBfNdlVh4aeu"
uri = "file://artifacts/france-royal/src/assets/politicians/darmanin.png"
type = "image"
title = "generated_image"

[[generated]]
id = "4T4bWQxH58SBbN3vEDXmd"
uri = "file://artifacts/france-royal/src/assets/politicians/crs.png"
type = "image"
title = "generated_image"

[[generated]]
id = "oAkRLIXWDLZdnCUWLr98x"
uri = "file://artifacts/france-royal/src/assets/politicians/agriculteur.png"
type = "image"
title = "generated_image"

[[generated]]
id = "x_OSOPe3FRd0_abuMelTa"
uri = "file://artifacts/france-royal/src/assets/politicians/pompier.png"
type = "image"
title = "generated_image"

[[generated]]
id = "KAvUW0W68Kin_mPvNVWi5"
uri = "file://artifacts/france-royal/src/assets/politicians/journaliste.png"
type = "image"
title = "generated_image"

[[generated]]
id = "vC5XLoy4U2hDn2xd6iIYS"
uri = "file://artifacts/france-royal/src/assets/politicians/lyceen.png"
type = "image"
title = "generated_image"

[[generated]]
id = "SotIo69qXBYhH387avUHk"
uri = "file://artifacts/france-royal/src/assets/politicians/taxi.png"
type = "image"
title = "generated_image"

[[generated]]
id = "MwTPZ8sYCp1bPwv4EUYyH"
uri = "file://artifacts/france-royal/src/assets/politicians/syndicat.png"
type = "image"
title = "generated_image"

[[generated]]
id = "QMVe3DMLRVcTdyR9XX1YL"
uri = "file://artifacts/france-royal/src/assets/politicians/sncf.png"
type = "image"
title = "generated_image"

[[generated]]
id = "EV3w3dxHHNcEud7uqdtEg"
uri = "file://artifacts/france-royal/src/assets/politicians/ouvrier.png"
type = "image"
title = "generated_image"

[[generated]]
id = "cmkFCCETRXVs21Qz4JENw"
uri = "file://artifacts/france-royal/src/assets/politicians/urssaf.png"
type = "image"
title = "urssaf inspector"
