import { CardDef } from "./types";

import zemmourImg from "../assets/politicians/zemmour.png";
import marineImg from "../assets/politicians/marine.png";
import melenchonImg from "../assets/politicians/melenchon.png";
import macronImg from "../assets/politicians/macron.png";
import bardellaImg from "../assets/politicians/bardella.png";
import piafImg from "../assets/politicians/piaf.png";
import bardotImg from "../assets/politicians/bardot.png";
import sarkozyImg from "../assets/politicians/sarkozy.png";
import hollandeImg from "../assets/politicians/hollande.png";
import giletsImg from "../assets/politicians/gilets.png";
import taxeImg from "../assets/politicians/taxe.png";
import chiracImg from "../assets/politicians/chirac.png";
import jmlepenImg from "../assets/politicians/jmlepen.png";
import philippeImg from "../assets/politicians/philippe.png";

export const CARDS: Record<string, CardDef> = {
  zemmour: {
    id: 'zemmour',
    fullName: "Éric Zemmour",
    name: "Reconquête",
    powerName: "Conversion",
    powerDesc: "40% de chance de retourner les troupes ennemies",
    cost: 3,
    color: "#1e3a5f",
    label: "ZEM",
    spawnCount: 1,
    baseHp: 500,
    baseDamage: 45,
    speed: 40,
    range: 35,
    attackSpeed: 1.0,
    radius: 14,
    special: "conversion",
    imagePath: zemmourImg,
  },
  marine: {
    id: 'marine',
    fullName: "Marine Le Pen",
    name: "La Présidente",
    powerName: "Tank Tour",
    powerDesc: "Tres résistante, fonce sur les tours",
    cost: 5,
    color: "#1d4ed8",
    label: "MLP",
    spawnCount: 1,
    baseHp: 2000,
    baseDamage: 150,
    speed: 25,
    range: 45,
    attackSpeed: 1.5,
    radius: 20,
    special: "building_target",
    imagePath: marineImg,
  },
  melenchon: {
    id: 'melenchon',
    fullName: "Jean-Luc Mélenchon",
    name: "L'Insoumis",
    powerName: "Escouade AoE",
    powerDesc: "Arrive avec 3 Insoumis, dégats de zone",
    cost: 4,
    color: "#ea580c",
    label: "JLM",
    spawnCount: 4,
    baseHp: 350,
    baseDamage: 55,
    speed: 45,
    range: 35,
    attackSpeed: 1.0,
    radius: 13,
    special: "aoe",
    imagePath: melenchonImg,
  },
  macron: {
    id: 'macron',
    fullName: "Emmanuel Macron",
    name: "En Marche !",
    powerName: "Reformes",
    powerDesc: "Rapide, mais coute 2 elixirs supplementaires aux allies",
    cost: 6,
    color: "#ca8a04",
    label: "MAC",
    spawnCount: 1,
    baseHp: 900,
    baseDamage: 180,
    speed: 90,
    range: 35,
    attackSpeed: 0.8,
    radius: 15,
    special: "tax_allies",
    imagePath: macronImg,
  },
  bardella: {
    id: 'bardella',
    fullName: "Jordan Bardella",
    name: "Le Jeune",
    powerName: "Rapide & Cheap",
    powerDesc: "Unite legere, tres rapide",
    cost: 2,
    color: "#0ea5e9",
    label: "BAR",
    spawnCount: 1,
    baseHp: 250,
    baseDamage: 30,
    speed: 85,
    range: 25,
    attackSpeed: 0.5,
    radius: 11,
    imagePath: bardellaImg,
  },
  piaf: {
    id: 'piaf',
    fullName: "Edith Piaf",
    name: "La Mome",
    powerName: "Soutien",
    powerDesc: "Soigne et booste les allies proches",
    cost: 4,
    color: "#e11d48",
    label: "PIAF",
    spawnCount: 1,
    baseHp: 400,
    baseDamage: 15,
    speed: 35,
    range: 70,
    attackSpeed: 1.0,
    radius: 13,
    special: "heal_boost",
    imagePath: piafImg,
  },
  bardot: {
    id: 'bardot',
    fullName: "Brigitte Bardot",
    name: "La Bete",
    powerName: "Splash",
    powerDesc: "Arrive avec 2 animaux devastateurs",
    cost: 3,
    color: "#15803d",
    label: "BBK",
    spawnCount: 3,
    baseHp: 300,
    baseDamage: 35,
    speed: 55,
    range: 30,
    attackSpeed: 0.8,
    radius: 12,
    special: "splash_pets",
    imagePath: bardotImg,
  },
  sarkozy: {
    id: 'sarkozy',
    fullName: "Nicolas Sarkozy",
    name: "Le President",
    powerName: "Garde du Corps",
    powerDesc: "Son garde absorbe les degats d'abord",
    cost: 5,
    color: "#7c3aed",
    label: "SAR",
    spawnCount: 2,
    baseHp: 700,
    baseDamage: 110,
    speed: 40,
    range: 35,
    attackSpeed: 1.1,
    radius: 15,
    special: "bodyguard",
    imagePath: sarkozyImg,
  },
  hollande: {
    id: 'hollande',
    fullName: "Francois Hollande",
    name: "Le Normal",
    powerName: "Scooter Panique",
    powerDesc: "Fonce en scooter puis se plante apres 7s",
    cost: 3,
    color: "#6b7280",
    label: "HOL",
    spawnCount: 1,
    baseHp: 400,
    baseDamage: 40,
    speed: 95,
    range: 30,
    attackSpeed: 0.9,
    radius: 13,
    special: "scooter_crash",
    imagePath: hollandeImg,
  },
  gilets: {
    id: 'gilets',
    fullName: "Les Gilets Jaunes",
    name: "La Manif",
    powerName: "Ralentissement",
    powerDesc: "Horde de 6, ralentit les ennemis proches",
    cost: 4,
    color: "#ca8a04",
    label: "GJ",
    spawnCount: 6,
    baseHp: 200,
    baseDamage: 20,
    speed: 30,
    range: 25,
    attackSpeed: 1.2,
    radius: 9,
    special: "slow_aura",
    imagePath: giletsImg,
  },
  taxe: {
    id: 'taxe',
    fullName: "Le Percepteur",
    name: "L'Impot",
    powerName: "Vol d'Elixir",
    powerDesc: "Vole 2 elixirs a l'ennemi a la pose",
    cost: 2,
    color: "#166534",
    label: "IMP",
    spawnCount: 1,
    baseHp: 300,
    baseDamage: 25,
    speed: 35,
    range: 30,
    attackSpeed: 1.0,
    radius: 12,
    special: "steal_elixir",
    imagePath: taxeImg,
  },
  chirac: {
    id: 'chirac',
    fullName: "Jacques Chirac",
    name: "Vieux Solide",
    powerName: "Regen HP",
    powerDesc: "Regenere 20 PV par seconde indefiniment",
    cost: 5,
    color: "#92400e",
    label: "CHI",
    spawnCount: 1,
    baseHp: 1200,
    baseDamage: 80,
    speed: 28,
    range: 40,
    attackSpeed: 1.3,
    radius: 17,
    special: "hp_regen",
    imagePath: chiracImg,
  },
  jmlepen: {
    id: 'jmlepen',
    fullName: "Jean-Marie Le Pen",
    name: "Le Vieux Demon",
    powerName: "Feu Ami",
    powerDesc: "Enorme degats de zone... meme sur les allies",
    cost: 6,
    color: "#7f1d1d",
    label: "JML",
    spawnCount: 1,
    baseHp: 1500,
    baseDamage: 200,
    speed: 20,
    range: 50,
    attackSpeed: 2.0,
    radius: 19,
    special: "friendly_fire",
    imagePath: jmlepenImg,
  },
  philippe: {
    id: 'philippe',
    fullName: "Edouard Philippe",
    name: "L'Efficace",
    powerName: "Le Truc Chiant",
    powerDesc: "Terne en apparence mais DPS le plus eleve du jeu",
    cost: 3,
    color: "#374151",
    label: "EPH",
    spawnCount: 1,
    baseHp: 450,
    baseDamage: 120,
    speed: 38,
    range: 35,
    attackSpeed: 0.4,
    radius: 13,
    imagePath: philippeImg,
  },
};

export const DECK = Object.values(CARDS);
