import { CardDef } from "./types";

import zemmourImg from "../assets/politicians/zemmour.png";
import marineImg from "../assets/politicians/marine.png";
import melenchonImg from "../assets/politicians/melenchon.png";
import macronImg from "../assets/politicians/macron.png";
import bardellaImg from "../assets/politicians/bardella.png";
import piafImg from "../assets/politicians/piaf.png";
import bardotImg from "../assets/politicians/bardot.png";
import sarkozyImg from "../assets/politicians/sarkozy.png";
import hollandeImg from "../assets/politicians/hollande.png";
import giletsImg from "../assets/politicians/gilets.png";
import taxeImg from "../assets/politicians/taxe.png";
import chiracImg from "../assets/politicians/chirac.png";
import jmlepenImg from "../assets/politicians/jmlepen.png";
import philippeImg from "../assets/politicians/philippe.png";
import degaulleImg from "../assets/politicians/degaulle.png";
import mitterrandImg from "../assets/politicians/mitterrand.png";
import giscardImg from "../assets/politicians/giscard.png";
import pompidouImg from "../assets/politicians/pompidou.png";
import napoleonImg from "../assets/politicians/napoleon.png";
import jeanneImg from "../assets/politicians/jeanne.png";
import louis14Img from "../assets/politicians/louis14.png";
import robespierreImg from "../assets/politicians/robespierre.png";
import dantonImg from "../assets/politicians/danton.png";
import attalImg from "../assets/politicians/attal.png";
import borneImg from "../assets/politicians/borne.png";
import castexImg from "../assets/politicians/castex.png";
import vallsImg from "../assets/politicians/valls.png";
import royalImg from "../assets/politicians/royal.png";
import fillonImg from "../assets/politicians/fillon.png";
import lemaireImg from "../assets/politicians/lemaire.png";
import darmaninImg from "../assets/politicians/darmanin.png";
import crsImg from "../assets/politicians/crs.png";
import agriculteurImg from "../assets/politicians/agriculteur.png";
import pompierImg from "../assets/politicians/pompier.png";
import journalisteImg from "../assets/politicians/journaliste.png";
import lyceenImg from "../assets/politicians/lyceen.png";
import taxiImg from "../assets/politicians/taxi.png";
import syndicatImg from "../assets/politicians/syndicat.png";
import sncfImg from "../assets/politicians/sncf.png";
import ouvrierImg from "../assets/politicians/ouvrier.png";
import urssafImg from "../assets/politicians/urssaf.png";

export const CARDS: Record<string, CardDef> = {
  zemmour: {
    id: 'zemmour',
    fullName: "Éric Zemmour",
    name: "Reconquête",
    powerName: "Conversion",
    powerDesc: "40% de chance de retourner les troupes ennemies",
    cost: 3,
    color: "#1e3a5f",
    label: "ZEM",
    spawnCount: 1,
    baseHp: 500,
    baseDamage: 45,
    speed: 40,
    range: 35,
    attackSpeed: 1.0,
    radius: 14,
    special: "conversion",
    imagePath: zemmourImg,
  },
  marine: {
    id: 'marine',
    fullName: "Marine Le Pen",
    name: "La Présidente",
    powerName: "Tank Tour",
    powerDesc: "Tres résistante, fonce sur les tours",
    cost: 5,
    color: "#1d4ed8",
    label: "MLP",
    spawnCount: 1,
    baseHp: 2000,
    baseDamage: 150,
    speed: 25,
    range: 45,
    attackSpeed: 1.5,
    radius: 20,
    special: "building_target",
    imagePath: marineImg,
  },
  melenchon: {
    id: 'melenchon',
    fullName: "Jean-Luc Mélenchon",
    name: "L'Insoumis",
    powerName: "Escouade AoE",
    powerDesc: "Arrive avec 3 Insoumis, dégats de zone",
    cost: 4,
    color: "#ea580c",
    label: "JLM",
    spawnCount: 4,
    baseHp: 350,
    baseDamage: 55,
    speed: 45,
    range: 35,
    attackSpeed: 1.0,
    radius: 13,
    special: "aoe",
    imagePath: melenchonImg,
  },
  macron: {
    id: 'macron',
    fullName: "Emmanuel Macron",
    name: "En Marche !",
    powerName: "Reformes",
    powerDesc: "Rapide, mais coute 2 elixirs supplementaires aux allies",
    cost: 6,
    color: "#ca8a04",
    label: "MAC",
    spawnCount: 1,
    baseHp: 900,
    baseDamage: 180,
    speed: 90,
    range: 35,
    attackSpeed: 0.8,
    radius: 15,
    special: "tax_allies",
    imagePath: macronImg,
  },
  bardella: {
    id: 'bardella',
    fullName: "Jordan Bardella",
    name: "Le Jeune",
    powerName: "Rapide & Cheap",
    powerDesc: "Unite legere, tres rapide",
    cost: 2,
    color: "#0ea5e9",
    label: "BAR",
    spawnCount: 1,
    baseHp: 250,
    baseDamage: 30,
    speed: 85,
    range: 25,
    attackSpeed: 0.5,
    radius: 11,
    imagePath: bardellaImg,
  },
  piaf: {
    id: 'piaf',
    fullName: "Edith Piaf",
    name: "La Mome",
    powerName: "Soutien",
    powerDesc: "Soigne et booste les allies proches",
    cost: 4,
    color: "#e11d48",
    label: "PIAF",
    spawnCount: 1,
    baseHp: 400,
    baseDamage: 15,
    speed: 35,
    range: 70,
    attackSpeed: 1.0,
    radius: 13,
    special: "heal_boost",
    imagePath: piafImg,
  },
  bardot: {
    id: 'bardot',
    fullName: "Brigitte Bardot",
    name: "La Bete",
    powerName: "Splash",
    powerDesc: "Arrive avec 2 animaux devastateurs",
    cost: 3,
    color: "#15803d",
    label: "BBK",
    spawnCount: 3,
    baseHp: 300,
    baseDamage: 35,
    speed: 55,
    range: 30,
    attackSpeed: 0.8,
    radius: 12,
    special: "splash_pets",
    imagePath: bardotImg,
  },
  sarkozy: {
    id: 'sarkozy',
    fullName: "Nicolas Sarkozy",
    name: "Le President",
    powerName: "Garde du Corps",
    powerDesc: "Son garde absorbe les degats d'abord",
    cost: 5,
    color: "#7c3aed",
    label: "SAR",
    spawnCount: 2,
    baseHp: 700,
    baseDamage: 110,
    speed: 40,
    range: 35,
    attackSpeed: 1.1,
    radius: 15,
    special: "bodyguard",
    imagePath: sarkozyImg,
  },
  hollande: {
    id: 'hollande',
    fullName: "Francois Hollande",
    name: "Le Normal",
    powerName: "Scooter Panique",
    powerDesc: "Fonce en scooter puis se plante apres 7s",
    cost: 3,
    color: "#6b7280",
    label: "HOL",
    spawnCount: 1,
    baseHp: 400,
    baseDamage: 40,
    speed: 95,
    range: 30,
    attackSpeed: 0.9,
    radius: 13,
    special: "scooter_crash",
    imagePath: hollandeImg,
  },
  gilets: {
    id: 'gilets',
    fullName: "Les Gilets Jaunes",
    name: "La Manif",
    powerName: "Ralentissement",
    powerDesc: "Horde de 6, ralentit les ennemis proches",
    cost: 4,
    color: "#ca8a04",
    label: "GJ",
    spawnCount: 6,
    baseHp: 200,
    baseDamage: 20,
    speed: 30,
    range: 25,
    attackSpeed: 1.2,
    radius: 9,
    special: "slow_aura",
    imagePath: giletsImg,
  },
  taxe: {
    id: 'taxe',
    fullName: "Le Percepteur",
    name: "L'Impot",
    powerName: "Perimetre Fiscal",
    powerDesc: "Cree une zone de controle 10s : chaque ennemi qui entre fait perdre 1 elixir a son camp",
    cost: 3,
    color: "#166534",
    label: "IMP",
    spawnCount: 0,
    baseHp: 0,
    baseDamage: 0,
    speed: 0,
    range: 0,
    attackSpeed: 0,
    radius: 0,
    special: "tax_zone",
    imagePath: taxeImg,
  },
  chirac: {
    id: 'chirac',
    fullName: "Jacques Chirac",
    name: "Vieux Solide",
    powerName: "Regen HP",
    powerDesc: "Regenere 20 PV par seconde indefiniment",
    cost: 5,
    color: "#92400e",
    label: "CHI",
    spawnCount: 1,
    baseHp: 1200,
    baseDamage: 80,
    speed: 28,
    range: 40,
    attackSpeed: 1.3,
    radius: 17,
    special: "hp_regen",
    imagePath: chiracImg,
  },
  jmlepen: {
    id: 'jmlepen',
    fullName: "Jean-Marie Le Pen",
    name: "Le Vieux Demon",
    powerName: "Feu Ami",
    powerDesc: "Enorme degats de zone... meme sur les allies",
    cost: 6,
    color: "#7f1d1d",
    label: "JML",
    spawnCount: 1,
    baseHp: 1500,
    baseDamage: 200,
    speed: 20,
    range: 50,
    attackSpeed: 2.0,
    radius: 19,
    special: "friendly_fire",
    imagePath: jmlepenImg,
  },
  philippe: {
    id: 'philippe',
    fullName: "Edouard Philippe",
    name: "L'Efficace",
    powerName: "Le Truc Chiant",
    powerDesc: "Terne en apparence mais DPS le plus eleve du jeu",
    cost: 3,
    color: "#374151",
    label: "EPH",
    spawnCount: 1,
    baseHp: 450,
    baseDamage: 120,
    speed: 38,
    range: 35,
    attackSpeed: 0.4,
    radius: 13,
    imagePath: philippeImg,
  },

  // ─── Présidents historiques ────────────────────────────────────────────────
  degaulle: {
    id: 'degaulle', fullName: "Charles de Gaulle", name: "Le Général",
    powerName: "Appel du 18 Juin", powerDesc: "Tank légendaire, régénère ses PV",
    cost: 6, color: "#1e40af", label: "DG", spawnCount: 1,
    baseHp: 2200, baseDamage: 140, speed: 28, range: 45, attackSpeed: 1.2, radius: 20,
    special: "hp_regen", imagePath: degaulleImg,
  },
  mitterrand: {
    id: 'mitterrand', fullName: "François Mitterrand", name: "Le Sphinx",
    powerName: "Force Tranquille", powerDesc: "Soigne les alliés proches",
    cost: 4, color: "#be123c", label: "MIT", spawnCount: 1,
    baseHp: 700, baseDamage: 60, speed: 32, range: 65, attackSpeed: 1.0, radius: 14,
    special: "heal_boost", imagePath: mitterrandImg,
  },
  giscard: {
    id: 'giscard', fullName: "Valéry Giscard d'Estaing", name: "V.G.E.",
    powerName: "Le Modéré", powerDesc: "Polyvalent, ni trop fort ni trop faible",
    cost: 4, color: "#0891b2", label: "VGE", spawnCount: 1,
    baseHp: 750, baseDamage: 90, speed: 45, range: 35, attackSpeed: 0.9, radius: 14,
    imagePath: giscardImg,
  },
  pompidou: {
    id: 'pompidou', fullName: "Georges Pompidou", name: "Le Banquier",
    powerName: "Garde Présidentielle", powerDesc: "Arrive avec 2 gardes du corps",
    cost: 5, color: "#475569", label: "POM", spawnCount: 3,
    baseHp: 800, baseDamage: 100, speed: 40, range: 35, attackSpeed: 1.0, radius: 15,
    special: "bodyguard", imagePath: pompidouImg,
  },

  // ─── Figures historiques ───────────────────────────────────────────────────
  napoleon: {
    id: 'napoleon', fullName: "Napoléon Bonaparte", name: "L'Empereur",
    powerName: "Grognards", powerDesc: "Arrive avec 4 grognards en formation",
    cost: 5, color: "#7c2d12", label: "NAP", spawnCount: 4,
    baseHp: 500, baseDamage: 80, speed: 42, range: 32, attackSpeed: 0.9, radius: 13,
    special: "aoe", imagePath: napoleonImg,
  },
  jeanne: {
    id: 'jeanne', fullName: "Jeanne d'Arc", name: "La Pucelle",
    powerName: "Sainte Charge", powerDesc: "Fonce sur les tours sans s'arrêter",
    cost: 4, color: "#fbbf24", label: "JDA", spawnCount: 1,
    baseHp: 1100, baseDamage: 130, speed: 50, range: 35, attackSpeed: 1.1, radius: 16,
    special: "building_target", imagePath: jeanneImg,
  },
  louis14: {
    id: 'louis14', fullName: "Louis XIV", name: "Le Roi Soleil",
    powerName: "L'État c'est moi", powerDesc: "Tank lourd, lent et imposant",
    cost: 8, color: "#a16207", label: "L14", spawnCount: 1,
    baseHp: 1800, baseDamage: 110, speed: 22, range: 45, attackSpeed: 1.8, radius: 22,
    imagePath: louis14Img,
  },
  robespierre: {
    id: 'robespierre', fullName: "Maximilien Robespierre", name: "L'Incorruptible",
    powerName: "La Terreur", powerDesc: "Dégâts de zone, même les alliés trinquent",
    cost: 5, color: "#991b1b", label: "ROB", spawnCount: 1,
    baseHp: 900, baseDamage: 160, speed: 35, range: 45, attackSpeed: 1.4, radius: 16,
    special: "friendly_fire", imagePath: robespierreImg,
  },
  danton: {
    id: 'danton', fullName: "Georges Danton", name: "L'Audacieux",
    powerName: "De l'Audace !", powerDesc: "Escouade rapide à dégâts de zone",
    cost: 4, color: "#7f1d1d", label: "DAN", spawnCount: 3,
    baseHp: 450, baseDamage: 70, speed: 50, range: 35, attackSpeed: 0.9, radius: 13,
    special: "aoe", imagePath: dantonImg,
  },

  // ─── Ministres / politiques contemporains ──────────────────────────────────
  attal: {
    id: 'attal', fullName: "Gabriel Attal", name: "Le Jeune Premier",
    powerName: "Communication Express", powerDesc: "Léger et très rapide",
    cost: 2, color: "#38bdf8", label: "ATT", spawnCount: 1,
    baseHp: 280, baseDamage: 40, speed: 90, range: 28, attackSpeed: 0.6, radius: 11,
    imagePath: attalImg,
  },
  borne: {
    id: 'borne', fullName: "Élisabeth Borne", name: "L'Ingénieure",
    powerName: "Soin Méthodique", powerDesc: "Soigne et booste les alliés",
    cost: 4, color: "#0e7490", label: "BOR", spawnCount: 1,
    baseHp: 500, baseDamage: 30, speed: 33, range: 70, attackSpeed: 1.0, radius: 13,
    special: "heal_boost", imagePath: borneImg,
  },
  castex: {
    id: 'castex', fullName: "Jean Castex", name: "L'Occitan",
    powerName: "Pas Cher", powerDesc: "Cheap et discret, fait son boulot",
    cost: 1, color: "#64748b", label: "CAS", spawnCount: 1,
    baseHp: 200, baseDamage: 25, speed: 50, range: 25, attackSpeed: 0.7, radius: 10,
    imagePath: castexImg,
  },
  valls: {
    id: 'valls', fullName: "Manuel Valls", name: "Le Catalan",
    powerName: "Coup Dur", powerDesc: "Frappe fort en mêlée",
    cost: 3, color: "#1e293b", label: "VAL", spawnCount: 1,
    baseHp: 600, baseDamage: 100, speed: 45, range: 25, attackSpeed: 0.8, radius: 13,
    imagePath: vallsImg,
  },
  royal: {
    id: 'royal', fullName: "Ségolène Royal", name: "La Présidente du Poitou",
    powerName: "Bienveillance", powerDesc: "Soutien à distance, soigne les alliés",
    cost: 3, color: "#db2777", label: "ROY", spawnCount: 1,
    baseHp: 380, baseDamage: 25, speed: 38, range: 75, attackSpeed: 1.0, radius: 12,
    special: "heal_boost", imagePath: royalImg,
  },
  fillon: {
    id: 'fillon', fullName: "François Fillon", name: "Le Costumé",
    powerName: "Cabinet Solide", powerDesc: "Robuste mais coûteux à entretenir",
    cost: 4, color: "#334155", label: "FIL", spawnCount: 1,
    baseHp: 900, baseDamage: 95, speed: 35, range: 35, attackSpeed: 1.0, radius: 14,
    imagePath: fillonImg,
  },
  lemaire: {
    id: 'lemaire', fullName: "Bruno Le Maire", name: "Le Ministre",
    powerName: "Prélèvement", powerDesc: "Vole 2 élixirs à l'ennemi à la pose",
    cost: 3, color: "#854d0e", label: "LMR", spawnCount: 1,
    baseHp: 350, baseDamage: 35, speed: 40, range: 30, attackSpeed: 1.0, radius: 12,
    special: "steal_elixir", imagePath: lemaireImg,
  },
  darmanin: {
    id: 'darmanin', fullName: "Gérald Darmanin", name: "L'Intérieur",
    powerName: "Renforts", powerDesc: "Arrive avec 2 agents de protection",
    cost: 4, color: "#1f2937", label: "DAR", spawnCount: 3,
    baseHp: 600, baseDamage: 85, speed: 42, range: 32, attackSpeed: 1.0, radius: 13,
    special: "bodyguard", imagePath: darmaninImg,
  },

  // ─── Groupes / corps de métier ─────────────────────────────────────────────
  crs: {
    id: 'crs', fullName: "Brigade CRS", name: "Forces de l'Ordre",
    powerName: "Charge Coordonnée", powerDesc: "Escouade de 5 agents équipés",
    cost: 4, color: "#0f172a", label: "CRS", spawnCount: 5,
    baseHp: 320, baseDamage: 45, speed: 38, range: 28, attackSpeed: 1.0, radius: 11,
    imagePath: crsImg,
  },
  agriculteur: {
    id: 'agriculteur', fullName: "Le Paysan", name: "Agriculteur en Colère",
    powerName: "Tracteur Bloquant", powerDesc: "Ralentit les ennemis autour de lui",
    cost: 2, color: "#65a30d", label: "AGR", spawnCount: 1,
    baseHp: 550, baseDamage: 30, speed: 22, range: 25, attackSpeed: 1.5, radius: 13,
    special: "slow_aura", imagePath: agriculteurImg,
  },
  pompier: {
    id: 'pompier', fullName: "Le Pompier", name: "Sapeur de Paris",
    powerName: "Lance à Eau", powerDesc: "Soigne les alliés à grande distance",
    cost: 3, color: "#dc2626", label: "POMP", spawnCount: 1,
    baseHp: 450, baseDamage: 20, speed: 45, range: 80, attackSpeed: 1.0, radius: 12,
    special: "heal_boost", imagePath: pompierImg,
  },
  journaliste: {
    id: 'journaliste', fullName: "Le Journaliste", name: "Reporter de Choc",
    powerName: "Micro Tendu", powerDesc: "Très cheap et rapide, peu de PV",
    cost: 1, color: "#7e22ce", label: "JRN", spawnCount: 1,
    baseHp: 150, baseDamage: 20, speed: 100, range: 28, attackSpeed: 0.5, radius: 9,
    imagePath: journalisteImg,
  },
  lyceen: {
    id: 'lyceen', fullName: "Les Lycéens", name: "Manif de Lycée",
    powerName: "Horde Jeune", powerDesc: "Essaim de 4 lycéens en grève",
    cost: 2, color: "#f59e0b", label: "LYC", spawnCount: 4,
    baseHp: 180, baseDamage: 18, speed: 50, range: 22, attackSpeed: 0.9, radius: 9,
    imagePath: lyceenImg,
  },
  taxi: {
    id: 'taxi', fullName: "Le Chauffeur de Taxi", name: "Taxi Parisien",
    powerName: "Charge Mécanique", powerDesc: "Très rapide, frappe en mêlée",
    cost: 2, color: "#facc15", label: "TAX", spawnCount: 1,
    baseHp: 340, baseDamage: 45, speed: 95, range: 22, attackSpeed: 0.7, radius: 12,
    imagePath: taxiImg,
  },
  syndicat: {
    id: 'syndicat', fullName: "Le Syndicaliste", name: "Le Représentant",
    powerName: "Mouvement Social", powerDesc: "Dégâts de zone et appel à la grève",
    cost: 4, color: "#b91c1c", label: "SYN", spawnCount: 2,
    baseHp: 500, baseDamage: 65, speed: 32, range: 38, attackSpeed: 1.1, radius: 14,
    special: "aoe", imagePath: syndicatImg,
  },
  sncf: {
    id: 'sncf', fullName: "Les Cheminots", name: "Bloqueurs SNCF",
    powerName: "Grève sur les Voies", powerDesc: "Horde de 6, ralentit les ennemis",
    cost: 4, color: "#1d4ed8", label: "SNCF", spawnCount: 6,
    baseHp: 220, baseDamage: 22, speed: 30, range: 25, attackSpeed: 1.2, radius: 9,
    special: "slow_aura", imagePath: sncfImg,
  },
  ouvrier: {
    id: 'ouvrier', fullName: "L'Ouvrier", name: "Bleu de Travail",
    powerName: "Marteau Lourd", powerDesc: "Frappe puissamment les bâtiments",
    cost: 3, color: "#a16207", label: "OUV", spawnCount: 1,
    baseHp: 700, baseDamage: 110, speed: 35, range: 28, attackSpeed: 1.3, radius: 14,
    special: "building_target", imagePath: ouvrierImg,
  },

  // ─── BOSS — admin-only, never unlocked through normal play ─────────────────
  urssaf: {
    id: 'urssaf', fullName: "L'URSSAF", name: "Le Contrôle",
    powerName: "Avis de redressement",
    powerDesc: "Transforme TOUTES les unités ennemies en factures non-payées. Les ennemis meurent lentement, leurs tours aussi. Vos tours deviennent invisibles. Dure jusqu'à la fin.",
    cost: 9, color: "#7f1d1d", label: "URSSAF", spawnCount: 0,
    baseHp: 0, baseDamage: 0, speed: 0, range: 0, attackSpeed: 0, radius: 0,
    special: "urssaf", imagePath: urssafImg,
  },
};

export const DECK = Object.values(CARDS);
