import { CardDef } from "./types";

import zemmourImg from "../assets/politicians/zemmour.png";
import marineImg from "../assets/politicians/marine.png";
import melenchonImg from "../assets/politicians/melenchon.png";
import macronImg from "../assets/politicians/macron.png";
import bardellaImg from "../assets/politicians/bardella.png";
import piafImg from "../assets/politicians/piaf.png";
import bardotImg from "../assets/politicians/bardot.png";
import sarkozyImg from "../assets/politicians/sarkozy.png";

export const CARDS: Record<string, CardDef> = {
  zemmour: {
    id: 'zemmour',
    fullName: "Éric Zemmour",
    name: "Reconquête",
    powerName: "Conversion",
    powerDesc: "Retourne les troupes ennemies",
    cost: 3,
    color: "#1e293b",
    label: "ZEM",
    spawnCount: 1,
    baseHp: 500,
    baseDamage: 45,
    speed: 40,
    range: 35,
    attackSpeed: 1.0,
    radius: 14,
    special: "conversion",
    imagePath: zemmourImg,
  },
  marine: {
    id: 'marine',
    fullName: "Marine Le Pen",
    name: "La Présidente",
    powerName: "Tank",
    powerDesc: "Très résistante, cible les tours",
    cost: 5,
    color: "#1d4ed8",
    label: "MLP",
    spawnCount: 1,
    baseHp: 2000,
    baseDamage: 150,
    speed: 25,
    range: 45,
    attackSpeed: 1.5,
    radius: 20,
    special: "building_target",
    imagePath: marineImg,
  },
  melenchon: {
    id: 'melenchon',
    fullName: "Jean-Luc Mélenchon",
    name: "L'Insoumis",
    powerName: "Escouade AoE",
    powerDesc: "Arrive avec 3 Insoumis, dégâts de zone",
    cost: 4,
    color: "#ea580c",
    label: "JLM",
    spawnCount: 4,
    baseHp: 350,
    baseDamage: 55,
    speed: 45,
    range: 35,
    attackSpeed: 1.0,
    radius: 13,
    special: "aoe",
    imagePath: melenchonImg,
  },
  macron: {
    id: 'macron',
    fullName: "Emmanuel Macron",
    name: "En Marche !",
    powerName: "Sprinter",
    powerDesc: "Vitesse de déplacement x2",
    cost: 6,
    color: "#ca8a04",
    label: "MAC",
    spawnCount: 1,
    baseHp: 900,
    baseDamage: 180,
    speed: 90,
    range: 35,
    attackSpeed: 0.8,
    radius: 15,
    special: "en_marche",
    imagePath: macronImg,
  },
  bardella: {
    id: 'bardella',
    fullName: "Jordan Bardella",
    name: "Le Jeune",
    powerName: "Rapide & Cheap",
    powerDesc: "Unité légère, très rapide",
    cost: 2,
    color: "#0ea5e9",
    label: "BAR",
    spawnCount: 1,
    baseHp: 250,
    baseDamage: 30,
    speed: 85,
    range: 25,
    attackSpeed: 0.5,
    radius: 11,
    imagePath: bardellaImg,
  },
  piaf: {
    id: 'piaf',
    fullName: "Édith Piaf",
    name: "La Môme",
    powerName: "Soutien",
    powerDesc: "Soigne et booste les alliés proches",
    cost: 4,
    color: "#e11d48",
    label: "PIAF",
    spawnCount: 1,
    baseHp: 400,
    baseDamage: 15,
    speed: 35,
    range: 70,
    attackSpeed: 1.0,
    radius: 13,
    special: "heal_boost",
    imagePath: piafImg,
  },
  bardot: {
    id: 'bardot',
    fullName: "Brigitte Bardot",
    name: "La Bête",
    powerName: "Splash",
    powerDesc: "Arrive avec 2 animaux dévastateurs",
    cost: 3,
    color: "#15803d",
    label: "BBK",
    spawnCount: 3,
    baseHp: 300,
    baseDamage: 35,
    speed: 55,
    range: 30,
    attackSpeed: 0.8,
    radius: 12,
    special: "splash_pets",
    imagePath: bardotImg,
  },
  sarkozy: {
    id: 'sarkozy',
    fullName: "Nicolas Sarkozy",
    name: "Le Président",
    powerName: "Garde du Corps",
    powerDesc: "Accompagné d'un garde qui absorbe les dégâts",
    cost: 5,
    color: "#7c3aed",
    label: "SAR",
    spawnCount: 2,
    baseHp: 700,
    baseDamage: 110,
    speed: 40,
    range: 35,
    attackSpeed: 1.1,
    radius: 15,
    special: "bodyguard",
    imagePath: sarkozyImg,
  }
};

export const DECK = Object.values(CARDS);
